services:
  backend:
    build:
      target: dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # - NEXT_PUBLIC_HMR_HOST=http://host.docker.internal # for macOS/Windows
      # - NEXT_PUBLIC_HMR_HOST=http://frontend # for Linux
      # - WATCHPACK_POLLING=true # webpack
      # - TURBOPACK_WATCH_POLLING=true # turbopack
