services:
  backend:
    container_name: backend
    build:
      context: ./backend
    expose:
      - "3001"
    networks:
      - app_network
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 5s
      retries: 3

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    expose:
      - "3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 5s
      retries: 3

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
