services:
  frontend:
    build:
      context: .
      target: runner
      dockerfile: Dockerfile
    expose:
      - "3000"
    networks:
      - app_network
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - app_network

networks:
  app_network:
